### ISSUE TITLE
Explain how to use email template functionality in plugin readme

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-email-handler#42]
The plugin readme instructions for the email template should be updated so that users can follow them to implement their own email templates with this plugin.

Context:
- [Comment in relevant docs issue](https://github.com/sensu/sensu-docs/pull/2220#pullrequestreview-365836539)
- [Slack discussion](https://sensu.slack.com/archives/C3MHLUP46/p1582741503054000)

Known updates needed:
- Identify the flags required for users to successfully use the email template.
- Explain that if you have more than one backend, they must all use the same email template.

**Comment by benh57** [comment]
Is it possible to reference a check annotation in an email template? This seems like the perfect place to store the 'playbook' url. 

To keep this relevant to this ticekt perhaps the example could be updated to source the playbook from the annotation, if this is possible, rather than hardcoding?   (i tried {{ Check.Annotations.playbook }} but it didnt seem to work)

**Comment by nixwiz** [comment]
@benh57 You're missing the leading period, try {{  .Check.Annotations.playbook }}, that worked for me.

**Comment by nixwiz** [comment]
@hillaryfraley I believe this has been addressed now, can you verify?

**Comment by hillaryfraley** [comment]
@nixwiz yes, it looks like everything is addressed.

**Comment by nixwiz** [comment]
@hillaryfraley closing based on that feedback.  Thank you!
