### ISSUE TITLE
Location of the email template file

### ISSUE THREAD

**Issue by twocs** [sensu/sensu-email-handler#58]
For Sensu Go, there might be a base Docker location where we run sensuctl commands, a sensu-backend, and a sensu-frontend. They can all have /etc/sensu/email_template.

Where is the file supposed to go? /etc/sensu/email_template is just too vague a description of the location.

**Comment by jspaleta** [comment]
Since the handlers such as this email handler are run from one of the sensu backend instances, any supporting file needed for handler operation would need to be available on all backends in the cluster during normal operation.

Would a note in the readme pointing out that the  email template file needs to exists on the sensu backends?

**Comment by twocs** [comment]
Yes, that would be useful. Maybe something like this?

https://github.com/sensu/sensu-email-handler#templates
The plugin provides an option to use a template as for the body of the email and is capable of using HTML for formatting the email. _The template file must needed for handler operation would need to be available on all backends in the cluster during normal operation._ An example is provided below:
